# This file is managed by Qt Creator, do not edit!

set("CMAKE_GENERATOR" "Ninja" CACHE "STRING" "" FORCE)
set("CMAKE_BUILD_TYPE" "Debug" CACHE "STRING" "" FORCE)
set("QT_QMAKE_EXECUTABLE" "/home/mrx/Qt/6.2.4/android_x86_64/bin/qmake" CACHE "FILEPATH" "" FORCE)
set("CMAKE_PREFIX_PATH" "/home/mrx/Qt/6.2.4/android_x86_64" CACHE "PATH" "" FORCE)
set("CMAKE_C_COMPILER" "/home/mrx/Qt/android-config-manually/sdk-download-by-qt/ndk/22.1.7171670/toolchains/llvm/prebuilt/linux-x86_64/bin/clang" CACHE "FILEPATH" "" FORCE)
set("CMAKE_CXX_COMPILER" "/home/mrx/Qt/android-config-manually/sdk-download-by-qt/ndk/22.1.7171670/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++" CACHE "FILEPATH" "" FORCE)
set("ANDROID_NATIVE_API_LEVEL" "23" CACHE "STRING" "" FORCE)
set("ANDROID_NDK" "/home/mrx/Qt/android-config-manually/sdk-download-by-qt/ndk/22.1.7171670" CACHE "PATH" "" FORCE)
set("CMAKE_TOOLCHAIN_FILE" "/home/mrx/Qt/android-config-manually/sdk-download-by-qt/ndk/22.1.7171670/build/cmake/android.toolchain.cmake" CACHE "FILEPATH" "" FORCE)
set("ANDROID_USE_LEGACY_TOOLCHAIN_FILE" "OFF" CACHE "BOOL" "" FORCE)
set("ANDROID_ABI" "x86_64" CACHE "STRING" "" FORCE)
set("ANDROID_STL" "c++_shared" CACHE "STRING" "" FORCE)
set("CMAKE_FIND_ROOT_PATH" "/home/mrx/Qt/6.2.4/android_x86_64" CACHE "PATH" "" FORCE)
set("QT_NO_GLOBAL_APK_TARGET_PART_OF_ALL" "ON" CACHE "BOOL" "" FORCE)
set("QT_HOST_PATH" "/home/mrx/Qt/6.2.4/gcc_64" CACHE "PATH" "" FORCE)
set("ANDROID_SDK_ROOT" "/home/mrx/Qt/android-config-manually/sdk-download-by-qt" CACHE "PATH" "" FORCE)
set("CMAKE_CXX_FLAGS_INIT" "-DQT_QML_DEBUG" CACHE "STRING" "" FORCE)